apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend
  labels:
    app: node-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-backend
  template:
    metadata:
      labels:
        app: node-backend
    spec:
      containers:
        - name: node-backend
          image: dhairyabahl/cloud-native-hackathon-node-backend
          ports:
            - containerPort: 8000
          env:
            - name: DB_CONNECTION_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: mongodb-secret
            - name: DB_CONNECTION_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mongodb-secret
            - name: DB_CONNECTION_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: database_url
                  name: mongodb-configmap
            - name: DB_CONNECTION_PORT
              value: '27017'
            - name: REDIS_PORT
              value: '6379'
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  key: redis_service
                  name: mongodb-configmap
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-password 
                  name: mongodb-secret
            - name: REDIS_EXPIRY_TIME
              value: '600'

---
apiVersion: v1
kind: Service
metadata:
  name: node-backend-service
spec:
  selector:
    app: node-backend
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      nodePort: 30564